apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: auth-ms
    spec:
      containers:
      - name: auth-ms
        image: devopspfa.azurecr.io/auth-ms:latest
        ports:
        - containerPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-ms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-ms
  template:
    metadata:
      labels:
        app: products-ms
    spec:
      containers:
      - name: products-ms
        image: devopspfa.azurecr.io/products-ms:latest
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchases-ms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: purchases-ms
  template:
    metadata:
      labels:
        app: purchases-ms
    spec:
      containers:
      - name: purchases-ms
        image: devopspfa.azurecr.io/purchases-ms:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-ms  # Change this to match your app labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: products-ms  # Change this to match your app labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: purchases-service
spec:
  selector:
    app: purchases-ms  # Change this to match your app labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

