version: '1'

services:
 product-ms:
    build:
      context: .
      dockerfile: products-ms/Dockerfile
    container_name: products-ms
    environment:
      PORT: 3000
      DB_HOST: "mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/commerce"
      JWT_SECRET: secret
    ports:
      - "3000:5000"  
    volumes:
      - ./products-ms:/app/products-ms  
    command: ["node", "dist/main.js"]

  auth-ms:
    build:
      context: .
      dockerfile: auth-ms/Dockerfile
    container_name: auth-ms
    environment:
      PORT: 8081
      DB_HOST: "mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/commerce"
      JWT_SECRET: secret
    ports:
      - "8081:8081"
    volumes:
      - ./auth-ms:/home/app/auth-ms
    command: ["./main"] 