apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-product-ms
spec:
  replicas: {{ .Values.productMS.replicas }}
  selector:
    matchLabels:
      app: product-ms
  template:
    metadata:
      labels:
        app: {{.Values.metadata.labels.app}}
    spec:
      containers:
        - name: product-ms
          image: {{ .Values.productMS.image }}
          ports:
            - containerPort: {{ .Values.productMS.port }}      
          env:
            - name: DB_HOST
              value: {{ .Values.productMS.dbHost }}
            - name: PORT
              value: "{{ .Values.productMS.port }}"
            - name: JWT_SECRET
              value: "{{ .Values.productMS.jwtSecret }}"
      imagePullSecrets:
        - name: {{ .Values.secrets.acr_secret_name }} 
  


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-ms
spec:
  replicas: {{ .Values.authMS.replicas }}
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: {{.Values.metadata.labels.app}}
    spec:
      containers:
        - name: auth-ms
          image: {{ .Values.authMS.image }}
          ports:
            - containerPort: {{ .Values.authMS.port }}
          env:
            - name: MONGODB_URI
              value: {{ .Values.authMS.MongoDBURI }}
            - name: DB_NAME
              value: {{ .Values.authMS.DBName }}
            - name: JWT_SECRET
              value: "{{ .Values.authMS.jwtSecret }}"
      imagePullSecrets:
        - name: {{ .Values.secrets.acr_secret_name }}  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-puchases-ms
spec:
  replicas: {{ .Values.purchasesMs.replicas }}
  selector:
    matchLabels:
      app: purchases-ms
  template:
    metadata:
      labels:
        app: {{.Values.metadata.labels.app}}
    spec:
      containers:
        - name: purchases-ms
          image: {{ .Values.purchasesMs.image }}
          ports:
            - containerPort: {{ .Values.purchasesMs.port }}
          env:
            - name: PORT
              value: "{{ .Values.purchasesMs.port }}"
            - name: PRODUCT_MS_URL
              value: load-balancer
            - name: PRODUCT_MS_PORT
              value: "3000"  
            - name: MONGODB_URI
              value: {{ .Values.purchasesMs.MongoDBURI }}
            - name: MONGODB_DATABASE
              value: {{ .Values.purchasesMs.MongoDBDatabase }}
            - name: JWT_SECRET
              value: "{{ .Values.purchasesMs.JWTSecret }}"
      imagePullSecrets:
        - name: {{ .Values.secrets.acr_secret_name }}