apiVersion: v1
kind: Service
metadata:
  name: pfa-chart
spec:
  selector:
    apiVersion: v1
    app: pfa-service
  ports:
    - protocol: TCP
      name: product-ms
      port: 3000
      targetPort: {{ .Values.productMS.port }}  
    - protocol: TCP
      name: auth-ms
      port: 8080 
      targetPort: {{ .Values.authMS.port }} 
    - protocol: TCP
      name: purchases-ms
      port: 5001 
      targetPort: {{ .Values.purchasesMs.port }}
  type: LoadBalancer

