apiVersion: v1
kind: Service
metadata:
  name: pfa-service
spec:
  selector:
    app: pfa-service
  ports:
    - protocol: TCP
      name: {{ .Release.Name }}-product-ms
      port: 3000
      targetPort: {{ .Values.productMS.port }}  
    - protocol: TCP
      name: {{ .Release.Name }}-auth-ms
      port: 8080 
      targetPort: {{ .Values.authMS.port }} 
    - protocol: TCP
      name: {{ .Release.Name }}-purchases-ms
      port: 5001 
      targetPort: {{ .Values.purchasesMs.port }}
  type: LoadBalancer

