apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer
spec:
  selector:
    app: product-ms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.productMS.port }}
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer2
spec:
  selector:
    app: auth-ms
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.authMS.port }}
  type: LoadBalancer