apiVersion: v1
kind: Service
metadata:
  name: all-apps-load-balancer
spec:
  selector:
    app: ""
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.productMS.port }}
      port: 8081 
      targetPort: {{ .Values.authMS.port }} 
    - protocol: TCP
      port: 8082 
      targetPort: {{ .Values.purchasesMs.port }}
  type: LoadBalancer
