apiVersion: v1
kind: Service
metadata:
  name: all-apps-load-balancer
spec:
  selector:
    app: {{.Values.metadata.labels.app}}
  ports:
    - protocol: TCP
      name: product-ms
      port: 3000
      targetPort: {{ .Values.productMS.port }}  
    - protocol: TCP
      name: auth-ms
      port: 8080 
      targetPort: {{ .Values.authMS.port }} 
    - protocol: TCP
      name: purchases-ms
      port: 5000 
      targetPort: {{ .Values.purchasesMs.port }}
  type: LoadBalancer


