productMS:
  replicas: 3
  image: pfaacr.azurecr.io/products-ms:latest
  dbHost: mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/commerce
  port: 3000
  stringPort: "3000"
  jwtSecret: secret

authMS:
  replicas: 1
  image: pfaacr.azurecr.io/auth-ms:latest
  MongoDBURI: mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/
  DBName: commerce
  port: 8080
  stringPort: "5000"
  jwtSecret: secret

secrets:
  acr_secret_name: pfaacr

purchasesMs:
  replicas: 1
  image: pfaacr.azurecr.io/purchases-ms:latest
  MongoDBURI: mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/
  MongoDBDatabase: commerce
  JWTSecret: secret
  port: 5001
  stringPort: 8080