productMS:
  replicas: 3
  image: pfaacr.azurecr.io/products-ms:latest
  dbHost: mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/commerce
  port: 3000
  jwtSecret: secret

authMS:
  replicas: 1
  image: pfaacr.azurecr.io/auth-ms:latest
  MongoDBURI: mongodb+srv://firasmosbehi:firas@cluster0.br9usu1.mongodb.net/
  DBName: commerce
  port: 8080
  jwtSecret: secret

secrets:
  acr_secret_name: pfaacr