 name: Create AKS cluster With Terraform infrastructure, monitored with prometheus and grafana
 on:
   workflow_dispatch:

 permissions:
   id-token: write
   contents: read
# jobs:
#   AKS-Cluster-Deployment:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: terraform
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3.1.0
#
#       - name: 'Az CLI login'
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: latest
#           cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}
#
#       - name: Terraform Init
#         run: terraform init
#
#       - name: Terraform Validate
#         run: terraform validate
#
#       - name: Terraform Plan
#         id: plan
#         run: terraform plan
#         continue-on-error: true
#
#       - name: Terraform Plan Status
#         if: steps.plan.outcome == 'failure'
#         run: exit 1
#
#       - name: Terraform Apply
#         if: steps.plan.outcome == 'success'
#         run: terraform apply -auto-approve
#
#       - name: Terraform Output
#         run: terraform output
#
#       - name: Configure kubectl
#         run: az aks get-credentials -n "pfaaks" -g "aks_terraform_rg"
#
#       - name: Deploy Helm Chart
#         run: |
#           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#           helm repo update
#           helm install pfa ../mychart/pfa-chart
#           helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
#           rm -rf ~/.kube

