name: auth-ms Pipeline

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest  # Or another suitable runner image
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
        
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
      - name: add env
        run: cd auth-ms && touch .env && echo 'MONGODB_URI=${{secrets.DB_HOST}}' >> .env && echo 'JWT_SECRET=${{secrets.JWT_SECRET}}' >> .env && echo 'DB_NAME=${{secrets.DB_NAME}}' >> .env && cat .env
      - name: install dependencies
        run: cd auth-ms && go mod tidy   
      - name: Build
        run: cd auth-ms && go build -o auth-ms-build .
      - name: Test
        run: cd auth-ms && go test

      - name: Create build directory
        run: mkdir build && cp auth-ms/auth-ms-build auth-ms/Dockerfile build

      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: auth-ms/auth-ms-build
  
  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: listing
        run: ls
        
      - name: Build image
        run: docker build -t firasmosbehi/auth-ms:latest .
        
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              
      - name: push image to docker hub
        run: docker push firasmosbehi/auth-ms:latest           
