name: auth-ms Pipeline

on:
  push:
    path:
      - 'auth-ms/**'
      - '.github/workflows/auth-ms-cicd.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest  # Or another suitable runner image
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
        
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
      - name: add env
        run: cd auth-ms && touch .env && echo 'MONGODB_URI=${{secrets.DB_HOST}}' >> .env && echo 'JWT_SECRET=${{secrets.JWT_SECRET}}' >> .env && echo 'DB_NAME=${{secrets.DB_NAME}}' >> .env && cat .env
      - name: install dependencies
        run: cd auth-ms && go mod tidy   
      - name: Build
        run: cd auth-ms && go build -o auth-ms-build .
      - name: Test
        run: cd auth-ms && go test

      - name: Create build directory
        run: mkdir build && cp auth-ms/auth-ms-build auth-ms/Dockerfile build

      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
  
  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: test
        run: ls    
        
      - name: Build image
        run: docker build -t auth-ms:latest .
        
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: devopspfa.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag auth-ms:latest devopspfa.azurecr.io/auth-ms:latest

      - name: Push Docker image to ACR
        run: |
          docker push devopspfa.azurecr.io/auth-ms:latest 