name: product-ms-pipeline

on:
  push:
    paths:
      - 'product-ms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enter the product-ms directory
        run: cd product-ms

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build # More specific dependency
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Run tests
        run: npm test
