name: product-ms-pipeline

on:
  push:
# todo: to be uncommented after testing    
#    paths:
#      - 'product-ms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: cd products-ms && npm install

      - name: Build NestJS app
        run: cd products-ms && npm run build

      
      - name: Create build directory
        run: mkdir build && cp -r products-ms/dist build && cp products-ms/nest-cli.json products-ms/package.json products-ms/Dockerfile products-ms/.dockerignore build


      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build

  test:
    runs-on: ubuntu-latest
    needs: build # More specific dependency
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Install dependencies
        run: cd build-artifact && npm install    


      - name: Run tests
        run: cd build-artifact && npm test
