name: product-ms-pipeline

on:
  push:
# todo: to be uncommented after testing    
#    paths:
#      - 'product-ms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: cd products-ms && npm install

      - name: Add Env
        run: echo "JWT_SECRET=${{secrets.JWT_SECRET}}" > .env && "DB_HOST=${{secrets.DB_HOST}}${{secrets.DB_NAME}}" > .env && "PORT=${{secrets.PRODUCT_MS_PORT}}" > .env

      - name: run tests
        run: cd products-ms && npm test

      - name: Build NestJS app
        run: cd products-ms && npm run build

      
      - name: Create build directory
        run: mkdir build && cp -r products-ms/dist build && cp products-ms/nest-cli.json products-ms/package.json products-ms/Dockerfile products-ms/.dockerignore build


      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build