name: product-ms-pipeline

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: cd products-ms && npm install

      - name: run tests
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          DB_HOST: ${{secrets.DB_HOST}}/${{secrets.DB_NAME}}
          PORT: ${{secrets.PRODUCT_MS_PORT}}
        run: cd products-ms && npm test

      - name: Build NestJS app
        run: cd products-ms && npm run build

      - name: Create build directory
        run: mkdir build && cp -r products-ms/dist build && cp products-ms/nest-cli.json products-ms/package.json products-ms/Dockerfile products-ms/.dockerignore build

      - name: Create build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Build image
        run: docker build -t product-ms:latest .

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: devopspfa.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag purchases-ms:latest devopspfa.azurecr.io/products-ms:latest

      - name: Push Docker image to ACR
        run: |
          docker push devopspfa.azurecr.io/products-ms:latest 
