name: purchases-ms-pipeline

on:
  push:
    paths:
      - 'purchases-ms/**'
      - '.github/workflows/purchases-ms-cicd.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd purchases-ms
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          MONGODB_URI: ${{secrets.DB_HOST}}
          MONGODB_DATABASE: ${{secrets.DB_NAME}}
          PORT: ${{secrets.PRODUCT_MS_PORT}}
        run: |
          cd purchases-ms
          python -m pytest

      - name: Build Docker image
        run: |
          cd purchases-ms
          docker build -t purchases-ms:latest .

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: devopspfa.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag purchases-ms:latest devopspfa.azurecr.io/purchases-ms:latest

      - name: Push Docker image to ACR
        run: |
          docker push devopspfa.azurecr.io/purchases-ms:latest
