name: purchases-ms-pipeline

on:
  push:
    paths:
      - 'purchases-ms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd purchases-ms
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          MONGODB_URI: ${{secrets.DB_HOST}}/
          MONGODB_DATABASE: ${{secrets.DB_NAME}}
          PORT: ${{secrets.PRODUCT_MS_PORT}}
        run: |
          cd purchases-ms
          python -m pytest

      - name: Build Docker image
        run: |
          cd purchases-ms
          docker build -t firasmosbehi/purchases-ms:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push firasmosbehi/purchases-ms:latest
