name: purchases-ms-pipeline

on:
  push:
    paths:
      - 'purchases-ms/**'
      - '.github/workflows/purchases-ms-cicd.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd purchases-ms
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dependency Vulnerability Scanning (Python)
        run: |
          cd purchases-ms
          pip install pip-audit
          pip-audit -o safety-report.txt  && cat safety-report.txt

      - name: Show Safety Report
        run: |
          cat purchases-ms/safety-report.txt
  
      - name: Run tests
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          MONGODB_URI: ${{secrets.DB_HOST}}
          MONGODB_DATABASE: ${{secrets.DB_NAME}}
          PORT: ${{secrets.PRODUCT_MS_PORT}}
        run: |
          cd purchases-ms
          python -m pytest
          
      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check Codecov report for errors
        run: |
          if [ -f codecov.txt ]; then
            if grep -q 'error' codecov.txt; then
              echo "Error found in Codecov report, stopping workflow."
              exit 1
            fi
          fi

      - name: Build Docker image
        run: |
          cd purchases-ms
          docker build -t purchases-ms:latest .

      - name: Container Security Scanning
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image purchases-ms:latest      

      - name: Login to Azure Container Registry ACR
        uses: azure/docker-login@v1
        with:
          login-server: pfaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag purchases-ms:latest pfaacr.azurecr.io/purchases-ms:latest

      - name: Push Docker image to ACR
        run: |
          docker push pfaacr.azurecr.io/purchases-ms:latest
